
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.3.0
// Created: 22/10/2018 - 09:11 a. m.
// This is a partial class file. The other one is vw_TicketsObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace BaseTicketRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class vw_TicketsObject : BaseObject, IMappeablevw_TicketsObject, IUniqueIdentifiable, IEquatable<vw_TicketsObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public vw_TicketsObject(): base()
        {


        }

        

        
        /// <summary>
        /// 
        /// </summary>
        public vw_TicketsObject(
			System.Int32 TicketId,
			System.String Numero,
			System.String Nombre,
			System.String Apellido,
			System.String Telefono,
			System.String Email,
			System.DateTime FechaTicket,
			System.String Descripcion,
			System.String Area): base()
        {

			_TicketId = TicketId;
			_Numero = Numero;
			_Nombre = Nombre;
			_Apellido = Apellido;
			_Telefono = Telefono;
			_Email = Email;
			_FechaTicket = FechaTicket;
			_Descripcion = Descripcion;
			_Area = Area;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _TicketId;
/// <summary>
/// 
/// </summary>
protected System.String _Numero;
/// <summary>
/// 
/// </summary>
protected System.String _Nombre;
/// <summary>
/// 
/// </summary>
protected System.String _Apellido;
/// <summary>
/// 
/// </summary>
protected System.String _Telefono;
/// <summary>
/// 
/// </summary>
protected System.String _Email;
/// <summary>
/// 
/// </summary>
protected System.DateTime _FechaTicket;
/// <summary>
/// 
/// </summary>
protected System.String _Descripcion;
/// <summary>
/// 
/// </summary>
protected System.String _Area;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 TicketId
        {
            get
            {
                return _TicketId;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Numero
        {
            get
            {
                return _Numero;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Email
        {
            get
            {
                return _Email;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.DateTime FechaTicket
        {
            get
            {
                return _FechaTicket;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Area
        {
            get
            {
                return _Area;
            }
            
        }
        
        #endregion

                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base.InternalOriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            vw_TicketsObject newObject;
            vw_TicketsObject newOriginalValue;

            newObject = (vw_TicketsObject) this.MemberwiseClone();
            if (base.InternalOriginalValue != null)
            {
                newOriginalValue = (vw_TicketsObject)this.OriginalValue().MemberwiseClone();
                newObject.InternalOriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new vw_TicketsObject OriginalValue()
        {
            return (vw_TicketsObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeablevw_TicketsObject.HydrateFields(
			System.Int32 TicketId,
			System.String Numero,
			System.String Nombre,
			System.String Apellido,
			System.String Telefono,
			System.String Email,
			System.DateTime FechaTicket,
			System.String Descripcion,
			System.String Area)
        {
        	_TicketId = TicketId;
			_Numero = Numero;
			_Nombre = Nombre;
			_Apellido = Apellido;
			_Telefono = Telefono;
			_Email = Email;
			_FechaTicket = FechaTicket;
			_Descripcion = Descripcion;
			_Area = Area;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeablevw_TicketsObject.GetFieldsForInsert()
        {
        
        
            throw new NotSupportedException();
        
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeablevw_TicketsObject.GetFieldsForUpdate()
        {
        
        
            throw new NotSupportedException();
        
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeablevw_TicketsObject.GetFieldsForDelete()
        {
        
            throw new NotSupportedException();
        
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeablevw_TicketsObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            
        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            vw_TicketsObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.TicketId, o.Numero, o.Nombre, o.Apellido, o.Telefono, o.Email, o.FechaTicket, o.Descripcion, o.Area};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(vw_TicketsObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeablevw_TicketsObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 TicketId, 
			System.String Numero, 
			System.String Nombre, 
			System.String Apellido, 
			System.String Telefono, 
			System.String Email, 
			System.DateTime FechaTicket, 
			System.String Descripcion, 
			System.String Area);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class vw_TicketsObjectList : ObjectList<vw_TicketsObject>
    {
    }
}

namespace BaseTicketRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class vw_TicketsObjectListView
        : ObjectListView<Objects.vw_TicketsObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public vw_TicketsObjectListView(Objects.vw_TicketsObjectList list): base(list)
        {
        }
    }
}


