
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.3.0
// Created: 20/10/2018 - 12:37 p. m.
// This is a partial class file. The other one is TicketsMapper.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using BaseTicketRules.Objects;
using BaseTicketRules.Entities;
using Cooperator.Framework.Core;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using System.Data.Common;
using System.Reflection;
using System;

namespace BaseTicketRules.Mappers
{

    /// <summary>
    /// Mapper for Tickets entity
    /// This class provide persistence methods for this entity
    /// </summary>
    public  partial class TicketsMapper
    {
        // /// <summary>
        // /// Enables GetObjectBySQLText and GetObjectListBySQLText methods.
        // /// </summary>
        //protected override bool SQLQueriesEnabled()
        //{
        //    return true;
        //}

        // /// <summary>
        // /// Checks for security ritghs
        // /// </summary>
        //protected override bool CheckForSecurityRights(SecurityRights action, TicketsList ObjectListOrEntityList)
        //{
        //    switch (action)
        //    {
        //        case SecurityRights.Read:
        //            return true;
        //        case SecurityRights.Insert:
        //            return true;
        //        case SecurityRights.Update:
        //            return true;
        //        case SecurityRights.Delete:
        //            return true;
        //    }
        //    return false;
        //}

    }

}


namespace BaseTicketRules.Loaders
{

    /// <summary>
    /// Loader for Tickets entity
    /// This class provide get methods for this entity
    /// </summary>
    public partial class TicketsLoader
    {
    }

}



