
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.3.0
// Created: 20/10/2018 - 12:37 p. m.
// This is a partial class file. The other one is database_firewall_rulesMapper.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using BaseTicketRules.Objects.sys;
using BaseTicketRules.Entities;
using Cooperator.Framework.Core;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using System.Data.Common;
using System.Reflection;
using System;

namespace BaseTicketRules.Mappers.sys
{

    /// <summary>
    /// Mapper for database_firewall_rules entity
    /// This class provide persistence methods for this entity
    /// </summary>
    public  partial class database_firewall_rulesMapper
    {
        // /// <summary>
        // /// Enables GetObjectBySQLText and GetObjectListBySQLText methods.
        // /// </summary>
        //protected override bool SQLQueriesEnabled()
        //{
        //    return true;
        //}

        // /// <summary>
        // /// Checks for security ritghs
        // /// </summary>
        //protected override bool CheckForSecurityRights(SecurityRights action, database_firewall_rulesList ObjectListOrEntityList)
        //{
        //    switch (action)
        //    {
        //        case SecurityRights.Read:
        //            return true;
        //        case SecurityRights.Insert:
        //            return true;
        //        case SecurityRights.Update:
        //            return true;
        //        case SecurityRights.Delete:
        //            return true;
        //    }
        //    return false;
        //}

    }

}


namespace BaseTicketRules.Loaders.sys
{

    /// <summary>
    /// Loader for database_firewall_rules entity
    /// This class provide get methods for this entity
    /// </summary>
    public partial class database_firewall_rulesLoader
    {
    }

}



