
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.3.0
// Created: 22/10/2018 - 09:11 a. m.
// This is a partial class file. The other one is AreaGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using BaseTicketRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace BaseTicketRules.Gateways
{
    /// <summary>
    /// 
    /// </summary>
    public partial class AreaGateway : BaseGateway<AreaObject, AreaObjectList>, IGenericGateway
    {

        #region "Singleton"

        static AreaGateway _instance;

        private AreaGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static AreaGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new AreaGateway();
                else {
                    AreaGateway inst = HttpContext.Current.Items["BaseTicketRules.AreaGatewaySingleton"] as AreaGateway;
                    if (inst == null) {
                        inst = new AreaGateway();
                        HttpContext.Current.Items.Add("BaseTicketRules.AreaGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "Area"; }
        }

        /// <summary>
        /// Return the AreaGateway type FullName
        /// </summary>
        protected override string RuleName
        {
            get {return typeof(AreaGateway).FullName;}
        }


        

        


        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, AreaObject entity)
        {
            
            IMappeableAreaObject Area = (IMappeableAreaObject)entity;
            Area.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(AreaObject entity)
        {

            IMappeableAreaObject Area = (IMappeableAreaObject)entity;
            return Area.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(AreaObject entity)
        {

            IMappeableAreaObject Area = (IMappeableAreaObject)entity;
            return Area.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(AreaObject entity)
        {

            IMappeableAreaObject Area = (IMappeableAreaObject)entity;
            return Area.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(AreaObject row, object[] parameters)
        {
            ((IMappeableAreaObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a AreaObject by execute a SQL Query Text
        /// </summary>
        public AreaObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a AreaObjectList by execute a SQL Query Text
        /// </summary>
        public AreaObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a AreaObject by calling a Stored Procedure
        /// </summary>
        public AreaObject GetOne(System.Int32 AreaId)
        {
            return base.GetOne(new AreaObject(AreaId));
        }


        // GetBy Objects and Params
            


        

        

        
        /// <summary>
        /// Delete Area
        /// </summary>
        public void Delete(System.Int32 AreaId)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Area_Delete", AreaId);
        }

        /// <summary>
        /// Delete Area
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 AreaId)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Area_Delete", AreaId);
        }

            

        


    


    


    


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








