
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.3.0
// Created: 20/10/2018 - 12:37 p. m.
// This is a partial class file. The other one is AreaObject.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using System;
using Cooperator.Framework.Core;
using Cooperator.Framework.Core.Exceptions;

namespace BaseTicketRules.Objects
{
    /// <summary>
    /// This class represents a Object of Area table.
    /// </summary>
    [Serializable]
    public partial class AreaObject
        // : IValidable
    {

        /// <summary>
        /// Called from class constructor.
        /// </summary>
        protected override void Initialize()
        {
        }

        // /// <summary>
        // /// Called after parameterized constructor. 
        // /// </summary>
        // protected override void Initialized()
        // {       
        // //Warnging: This method is only called by parameterized contructors.
        // }

        // /// <summary>
        // /// When IValidable is implemented, this method is invoked by Gateway before Insert or Update to validate Object.
        // /// </summary>
        // public void Validate()
        // {
        //     string msgRequired = "{0} can't be null";
        //     string msgOutOfRange = "{0} incorrect value";

        //     if (string.IsNullOrEmpty(this.Descripcion)) throw new RuleValidationException(string.Format(msgRequired, "Descripcion"));
        
        // }
    }

    /// <summary>
    /// This class represents a record set of Area table.
    /// </summary>
    public partial class AreaObjectList
    {
         // /// <summary>
         // /// Returns a typed Dataset based on its content.
         // /// </summary>
         // public override System.Data.DataSet ToDataSet()
         // {
         //    YOUR_TYPED_DATASET MyDataSet = new YOUR_TYPED_DATASET();
         //    ObjectListHelper<AreaObject, AreaObjectList> Exporter = new ObjectListHelper<AreaObject, AreaObjectList>();
         //    Exporter.FillDataSet(MyDataSet, this);
         //    return MyDataSet;
         // }
    }
}

namespace BaseTicketRules.Views
{
    /// <summary>
    /// This class represents a view of an collection of AreaObjects.
    /// </summary>
    public partial class AreaObjectListView
    {
    }
}


