
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.3.0
// Created: 20/10/2018 - 12:37 p. m.
// This is a partial class file. The other one is AreaMapper.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using BaseTicketRules.Entities;
using BaseTicketRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data.Common;
using System.Reflection;
using System.Web;
using System.Data;

namespace BaseTicketRules.Mappers
{

    
    /// <summary>
    /// 
    /// </summary>
    public partial class AreaMapper : BaseGateway<AreaObject, AreaObjectList>, IGenericGateway
    {


        #region "Singleton"

        static AreaMapper _instance;

        private AreaMapper()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static AreaMapper Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new AreaMapper();
                else {
                    AreaMapper inst = HttpContext.Current.Items["BaseTicketRules.AreaMapperSingleton"] as AreaMapper;
                    if (inst == null) {
                        inst = new AreaMapper();
                        HttpContext.Current.Items.Add("BaseTicketRules.AreaMapperSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"AreaId"};
            return s;
        }

        /// <summary>
        ///
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(AreaObject);
        }

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "Area"; }
        }

        /// <summary>
        /// Return the AreaMapper type FullName
        /// </summary>
        protected override string RuleName
        {
            get {return typeof(AreaMapper).FullName;}
        }


        

        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, AreaObject entity)
        {
            
            IMappeableAreaObject Area = (IMappeableAreaObject)entity;
            Area.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1));
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(AreaObject entity)
        {

            IMappeableAreaObject Area = (IMappeableAreaObject)entity;
            return Area.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(AreaObject entity)
        {

            IMappeableAreaObject Area = (IMappeableAreaObject)entity;
            return Area.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(AreaObject entity)
        {

            IMappeableAreaObject Area = (IMappeableAreaObject)entity;
            return Area.GetFieldsForDelete();
        }


        /// <summary>
        /// Raised after insert and update
        /// </summary>
        protected override void UpdateObjectFromOutputParams(AreaObject entity, object[] parameters)
        {
            // Update properties from Output parameters
            ((IMappeableAreaObject) entity).UpdateObjectFromOutputParams(parameters);
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


          


        /// <summary>
        /// Get a AreaObject by execute a SQL Query Text
        /// </summary>
        public AreaObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a AreaObjectList by execute a SQL Query Text
        /// </summary>
        public AreaObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        
        /// <summary>
        /// 
        /// </summary>
        public AreaObject GetOne(System.Int32 AreaId)
        {
            return base.GetOne(new AreaObject(AreaId));
        }
        

        // GetOne By Objects and Params
            


        


        

        
        /// <summary>
        /// 
        /// </summary>
        public void Delete(System.Int32 AreaId)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Area_Delete", AreaId);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 AreaId)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Area_Delete", AreaId);
        }


        // Delete By Objects and Params
            



        


    


    


    


        //Database Queries 
        


        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }


}

namespace BaseTicketRules.Wrappers
{
    /// <summary>
    /// 
    /// </summary>
    public partial class AreaMapperWrapper
    {

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            return Instance().GetPKPropertiesNames();
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return Instance().GetMappingType();
        }



        /// <summary>
        /// 
        /// </summary>
        public BaseTicketRules.Mappers.AreaMapper Instance()
        {
            return BaseTicketRules.Mappers.AreaMapper.Instance(); 
        }
        
        
        /// <summary>
        /// Get a AreaEntity by calling a Stored Procedure
        /// </summary>
        public Objects.AreaObject GetOne(System.Int32 AreaId) {
            return Instance().GetOne( AreaId);
        }
        

        // GetBy Objects and Params
            

        

        /// <summary>
        /// GetAll AreaObject 
        /// </summary>
        public Objects.AreaObjectList GetAll(){  
            return Instance().GetAll();
        }

        
        

            

        
        /// <summary>
        /// Delete Area 
        /// </summary>
        public void Delete(System.Int32 AreaId){
            Instance().Delete(AreaId);
        }

        /// <summary>
        /// Delete AreaObject 
        /// </summary>
        public void Delete(Objects.AreaObject entity ){
            Instance().Delete(entity);
        }

        /// <summary>
        /// Save AreaObject  
        /// </summary>
        public void Save(Objects.AreaObject entity){
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert AreaObject 
        /// </summary>
        public void Insert(Objects.AreaObject entity){
            Instance().Insert(entity);
        }

        /// <summary>
        /// Save Area 
        /// </summary>
        public void Save(System.Int32 AreaId, System.String Descripcion){
            Objects.AreaObject entity = Instance().GetOne(AreaId);
            if (entity == null)
                throw new ApplicationException(String.Format("Entity not found. IUniqueIdentifiable Values: {0} = {1}", "AreaId", AreaId));

            entity.Descripcion = Descripcion;
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert AreaObject
        /// </summary>
        public void Insert(System.String Descripcion){
            Objects.AreaObject entity = new Objects.AreaObject();

            entity.Descripcion = Descripcion;
            Instance().Insert(entity);
        }

        


        //Database Queries 
        


    }
}





namespace BaseTicketRules.Loaders
{

    /// <summary>
    /// 
    /// </summary>
    public partial class AreaLoader<T> : BaseLoader< T, AreaObject, ObjectList<T>>, IGenericGateway where T : AreaObject, new()
    {

        #region "Singleton"

        static AreaLoader<T> _instance;

        private AreaLoader()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static AreaLoader<T> Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new AreaLoader<T>();
                else {
                    AreaLoader<T> inst = HttpContext.Current.Items["BaseTicketRules.AreaLoaderSingleton"] as AreaLoader<T>;
                    if (inst == null) {
                        inst = new AreaLoader<T>();
                        HttpContext.Current.Items.Add("BaseTicketRules.AreaLoaderSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"AreaId"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(AreaObject);
        }


        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "Area"; }
        }

        

        

        
        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, AreaObject entity)
        {
            
            IMappeableAreaObject Area = (IMappeableAreaObject)entity;
            Area.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        



        /// <summary>
        /// Get a Area by execute a SQL Query Text
        /// </summary>
        public T GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a AreaList by execute a SQL Query Text
        /// </summary>
        public ObjectList<T> GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }

        
        /// <summary>
        /// GetOne By Params
        /// </summary>
        public T GetOne(System.Int32 AreaId)
        {
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "Area_GetOne", AreaId);
        }
        


        // GetOne By Objects and Params
            


        


        

        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion

    }
}





