
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.3.0
// Created: 20/10/2018 - 12:37 p. m.
// This is a partial class file. The other one is AreaObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace BaseTicketRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class AreaObject : BaseObject, IMappeableAreaObject, IUniqueIdentifiable, IEquatable<AreaObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public AreaObject(): base()
        {

			_AreaId =  ValuesGenerator.GetInt32;

        }

        
        /// <summary>
        /// 
        /// </summary>
        public AreaObject(
			System.Int32 AreaId): base()
        {

			_AreaId = AreaId;

            Initialized();
        }
        

        
        /// <summary>
        /// 
        /// </summary>
        public AreaObject(
			System.Int32 AreaId,
			System.String Descripcion): base()
        {

			_AreaId = AreaId;
			_Descripcion = Descripcion;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _AreaId;
/// <summary>
/// 
/// </summary>
protected System.String _Descripcion;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 AreaId
        {
            get
            {
                return _AreaId;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            
            set
            {
                base.PropertyModified();
                _Descripcion = value;
                
            }
            
        }
        
        #endregion

                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base.InternalOriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            AreaObject newObject;
            AreaObject newOriginalValue;

            newObject = (AreaObject) this.MemberwiseClone();
            if (base.InternalOriginalValue != null)
            {
                newOriginalValue = (AreaObject)this.OriginalValue().MemberwiseClone();
                newObject.InternalOriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new AreaObject OriginalValue()
        {
            return (AreaObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableAreaObject.HydrateFields(
			System.Int32 AreaId,
			System.String Descripcion)
        {
        	_AreaId = AreaId;
			_Descripcion = Descripcion;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableAreaObject.GetFieldsForInsert()
        {
        
        
            object[] _myArray = new object[2];
            _myArray[0] = _AreaId;
			_myArray[1] = _Descripcion;
			
            return _myArray;
        
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableAreaObject.GetFieldsForUpdate()
        {
        
        
            
            object[] _myArray = new object[2];
            _myArray[0] = _AreaId;
			_myArray[1] = _Descripcion;
			
            return _myArray;
        
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableAreaObject.GetFieldsForDelete()
        {
        
            object[] _myArray = new object[1];
            _myArray[0] = _AreaId;
			
            return _myArray;
        
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableAreaObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _AreaId = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            AreaObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.AreaId};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(AreaObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableAreaObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 AreaId, 
			System.String Descripcion);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class AreaObjectList : ObjectList<AreaObject>
    {
    }
}

namespace BaseTicketRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class AreaObjectListView
        : ObjectListView<Objects.AreaObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public AreaObjectListView(Objects.AreaObjectList list): base(list)
        {
        }
    }
}


